### ISSUE TITLE
README missing (require)

### ISSUE THREAD

**Issue by jimrthy** [weavejester/integrant-repl#1]
I'm trying to follow along at home, and I had to add set-prep! to to the :require clause in my dev's ns form.

It's a really minor nit, but seemed worth mentioning.

**Comment by jimrthy** [comment]
After that, I wound up confused because I got an "AssertionError: Assert failed (map? system) integrant.core/resume (core.cljc 215)" when I tried to run (reset).

That problem was that I wasn't running (go) first. I'm used to setting things up so I can just run (reset) at the beginning without needing to remember that (go) even exists.

Thanks for another great tool!

**Comment by jimrthy** [comment]
Oh, yeah. And then I had to look at the code to figure out that my system was getting stored in integrant.repl/system.

edit: Yes, that was another bit of goofiness on my part, since it's getting referred into the dev ns.

**Comment by weavejester** [comment]
Thanks for the bug report. I've added some more explanation to the README and fixed the typo in the example code.
