### ISSUE TITLE
Recommend set-refresh-dirs

### ISSUE THREAD

**Issue by vemv** [weavejester/integrant-repl#16]
Hi,

in conversation with an Integrant user we found that https://github.com/weavejester/integrant-repl could make an explicit mention of `set-refresh-dirs`, so that it's clear that that's its normal/ideal usage.

Probably not much argumentation is needed in favor of `set-refresh-dirs`, as it's already templated [here](https://github.com/duct-framework/duct/blob/778942aa85999c74592ed60ae23b6112bf385240/lein-template/resources/leiningen/new/duct/base/dev.clj#L26) and [here](https://github.com/stuartsierra/reloaded/blob/1742037b053d355c5f7b99e3133796939876094d/src/leiningen/new/reloaded/templates/dev.clj#L26)

Would PR myself this small improvement, but currently I can't due to IP concerns.

Thanks - V

**Comment by weavejester** [comment]
You mean add a note to the README?

**Comment by vemv** [comment]
Yeah I think that's enough

**Comment by vemv** [comment]
Thanks!
