### ISSUE TITLE
Wrong parameter for clojure.tools.namespace.repl/set-refresh-dirs in README.md

### ISSUE THREAD

**Issue by julianwegkamp** [weavejester/integrant-repl#18]
Small error in the README.md. clojure.tools.namespace.repl/set-refresh-dirs expects a variable number of parameters instead of a vector.

http://clojure.github.io/tools.namespace/#clojure.tools.namespace.repl/set-refresh-dirs

**Comment by weavejester** [comment]
Fixed. Thanks for the issue report.
