### ISSUE TITLE
Go conflicts with core.async/go

### ISSUE THREAD

**Issue by vspinu** [weavejester/integrant-repl#5]
This conflict is actually quite unfortunate because one would like to have both go's as top symbols. Async is pretty popular by now. Maybe `igo`?

**Comment by weavejester** [comment]
You can always rename the function yourself if you find yourself with a conflict:

```clojure
(ns dev
  (:require [integrant.repl :refer :all :rename {go igo}]))
```

Conflicts are inevitable because we have a limited number of appropriate words in the English language. I'm using `go` because that's the name Stuart Sierra used for this in his original reloaded workflow idea.

**Comment by vspinu** [comment]
Yeh, I guess you are right.
