### ISSUE TITLE
Add `keys` arg

### ISSUE THREAD

**Issue by WhittlesJr** [weavejester/integrant-repl#9]
I was surprised when I realized that you don't expose Integrant's overloading for passing a list of keys to init/halt!/suspend!/resume/etc. 

I'm working on a PR at the moment but stop me if you don't want this or you've found that it doesn't work.

**Comment by weavejester** [comment]
As long as the keys are optional arguments, this sounds like a useful addition.

**Comment by madstap** [comment]
There doesn't seem to have been a release since this was merged. Would be grateful if you could cut a release. (And/or add a deps.edn so we can use it as a git dep.)

**Comment by weavejester** [comment]
Released 0.3.2. Sorry about the delay.
